= awesome-wiki
"kmmin78
" <kmmin78@gmail.com>, "Chen Steve" <neropsys@gmail.com>, "Francesco Jo" <nimbusob@gmail.com>
// Metadata:
:description: Wiki 프로젝트
:keywords: spring-boot, jpa-hibernate, junit5, spock-groovy, spring-rest-docs, tdd, kotlin, gradle
// Settings:
:doctype: book
:toc: left
:toclevels: 4
:sectlinks:
:icons: font
// Refs:
:link-todo-sheets: https://docs.google.com/spreadsheets/d/1xWtMZ2Ng69OcFMIkfMSQvYUPtqB-fzVKMoopEGIuOIA
:link-todo-issues: https://github.com/f-lab-edu/awesome-wiki/issues
:link-detekt: https://arturbosch.github.io/detekt/index.html
:link-clean-architecture: https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html
:link-moduler-monolith: https://medium.com/design-and-tech-co/modular-monoliths-a-gateway-to-microservices-946f2cbdf382

[[overview]]
== 개요

Spring framework 를 이용한 다중 접속 애플리케이션에서 발생하는 어려움을 해결하며 공부하기 위한 프로젝트입니다.

최대한 효율적으로 TDD 를 연습하기 위해 link:{link-todo-sheets}[할 일 목록 Google sheets] 와 link:{link-todo-issues}[Issue Kanban board] 를 적극 활용하고 있습니다.

[[running-tests]]
=== 테스트 실행
이 프로젝트에서는 Unit / Integration / End to end 테스트들을 종류별로 구분해 구현하고 있습니다. 테스트들은 martinFowler.com 의 link:https://martinfowler.com/articles/practical-test-pyramid.html[The practical test pyramid] 라는 글에 따라 규모별로 구분하고 있으모, 각 테스트를 실행하는 gradle task 명은 아래와 같습니다.

* `test` - 등록된 모든 테스트를 실행합니다. 시간이 가장 많이 걸립니다.
* `unitTest` - Unit test 들만을 모두 실행합니다. 시간이 가장 적게 걸립니다.
* `integrationTest` - Integration test 들만을 모두 실행합니다. Unit test 보다는 실행 시간이 좀 더 걸립니다.
* `e2eTest` - End to end test 들만을 모두 실행합니다. End to end test 를 일컫는 말들은 여러 가지가 있지만 이 프로젝트에서는 API 가 정상 동작하는지를 확인하는 테스트를 의미합니다.

[[code-quality-measurement]]
=== 코드 품질 측정

서로 다른 코딩 규칙으로 인해 코드 리뷰에 스타일링 지적 같은 불필요한 시간 낭비가 발생하는 일을 줄이고자, link:{link-detekt}[detekt] 를 이용해 코딩 스타일과 사전 실수를 관리하고 있습니다.

또한 자동화된 test 를 항상 실행해 코드를 안전하게 변경 및 통합하고자 노력했습니다.

아래 gradle task 를 실행하면 이 프로젝트에서 코드 품질을 측정할 수 있습니다.

[source,shell script]
----
./gradlew detekt jacocoTestReport
----

각 Task 들의 설명은 다음과 같습니다.

- `detekt`: link:{link-detekt}[detekt] 를 실행. Kotlin 정적 분석 실행.
- `jacocoTestReport`: 테스트 실행 및 테스트의 코드 커버리지 측정.

[[project-structure]]
=== 프로젝트 모듈 및 구조 설명

* 추후 Microservice로 전환이 용이한 형태인 link:{link-moduler-monolith}[Moduler Monolith]를 gradle의 multi-module을 이용해 구성했습니다.

* link:{link-clean-architecture}[Clean Architecture]의 영감을 받아 module의 구성요소와 의존 방향을 설계했습니다.

현재 프로젝트는 크게 스프링 관련 코드, 즉 entry point가 있는 app-main 모듈과 도메인/비즈니스 로직을 모아둔 app-core모듈로 나뉩니다.

도메인과 프레임워크 코드를 모듈로 분리하여 프로젝트가 spring에 의존하지 않고 약간의 수정으로 다른 프레임워크에서 실행 가능하도록 하는것이 목적입니다.

프로젝트는 다음 3개의 모듈로 구성이 되어있고, 각 모듈의 개요는 다음과 같습니다.

* `app-core` : link:{link-clean-architecture}[Clean Architecture]에서 inner circles(그 중에서도 Entities)에 해당하는 부분입니다. +
               위키 서비스의 Domain과 Business Rules를 구성하고 있으며, 외부 모듈에 의존하지 않습니다. +
               설계한 도메인 모델과 서비스를 모아둔 모듈입니다. 문서화를 위한 annotation,과 도메인을 사용하면서 발생하는 exception도 정의되어 있습니다. +
               이러한 특성 덕분에 이식성이 높아짐을 얻을 수 있습니다.

app-core의 패키지는 다음과 같이 구성되어 있습니다.

** `domain` - 도메인의 구현체 패키지입니다. app-main 프로젝트에서는 도메인의 인터페이스만 사용 가능합니다.
*** `document` - 위키 문서 자체의 도메인입니다.
*** `user` - 문서를 작성한 유저의 도메인입니다

* `app-main` : link:{link-clean-architecture}[Clean Architecture]의 outer circles에 해당하는 부분입니다. +
               여기서부터 Use Cases를 포함하여 outer circles의 대부분의 계층이 포함됩니다. +
               app-core 모듈을 의존하며, Web Framework(Spring)와 Database, Client, UI 등 외부 미들웨어 혹은 라이브러리와 직접 의존하는 모듈입니다. +
               여러 계층을 한 모듈에 담아냈기 때문에, 추후 분리될 가능성이 있는 모듈입니다.

* `app-lib` : 위키 서비스의 도메인과 관련 없지만, 자주 사용하는 유틸리티성 메소드를 모아둔 모듈입니다.

